### ISSUE TITLE
_on_stream_error - will terminate: undefined entity

### ISSUE THREAD

**Issue by vinnitu** [xmppo/node-xmpp-bosh#25]
[2012-04-06 13:49:09.235] [ERROR] [xmpp-proxy.js] - 30f0d096-0078-4a7c-b6e2-05d684f37a58 363a37cf-6e8e-461c-829d-b3899ef197f4 _on_stream_error - will terminate: undefined entity

and such xml

&lt;message from='one@chat' to='two@chat' type='chat'&gt;&lt;body&gt;salut &amp;agrave; tous, on peut chatter un peu ?&lt;/body&gt;&lt;/message&gt;

we can see - expat parse() failed, but why?... if expat doesn't known entity agrave it doesn't mean session must terminate, imho

what do you think?

**Comment by dhruvbird** [comment]
@vinnitu Can you try opening this on the node-expat issue list.
Do you have a small test case that shows that node-expat::parse() fails on &amp;agrave; ?

Update: I found an open issue here: https://github.com/astro/node-expat/issues/6

Update2: I would think that valid clients should send the accented 'a' character (&agrave;) rather than &amp;agrave;

**Comment by vinnitu** [comment]
for me solution is 'Update 2' ;-) but it was just interesting situation
