### ISSUE TITLE
SASL support for X-FACEBOOK-PLATFORM

### ISSUE THREAD

**Issue by immanuel** [xmppo/node-xmpp-bosh#37]
I have the BOSH server running on nodejitsu, with a strophe client. I am trying to authenticate a user for Facebook chat using the X-FACEBOOK-PLATFORM. I have also added 'chat.facebook.com' to the no-TLS list in the conf file. 

But, when chat.facebook.com offers the choice between DIGEST-MD5 and X-FACEBOOK-PLATFORM, the app defaults to DIGEST-MD5.

Is this an issue with node-xmpp-bosh or nodejitsu? Is there a way to solve this? 

I have tested the strophe client with PunJab and X-FACEBOOK-PLATFORM does work.

**Comment by dhruvbird** [comment]
Authentication is handled by the xmpp client, so most likely you need to get strophe to fix it.

I am unsure of how (or whether) facebook changes the auth mechanisms once SSL is enabled. It is possible that they use a weaker form of auth. once SSL is enabled since the connection is now encrypted. Do you know if Punjab supports SSL upgrades? Try to check if Punjab is also not upgrading the connection. As a first step, try to leave the no-TLS list in the config file empty.

**Comment by dhruvbird** [comment]
@immanuel Were you able to figure out where the issue is?

**Comment by immanuel** [comment]
Hi - it was an issue with nodejitsu. There was no support for https and hence DIGEST-MD5 was picked up by default.
