### ISSUE TITLE
log4js has no method 'consoleAppender'

### ISSUE THREAD

**Issue by sonnyp** [xmppo/node-xmpp-bosh#38]
Step to reproduce:
npm install node-xmpp-bosh
./run-server,js

I didn't have the time to look at it yet but since it looks critical I report the problem.

**Comment by sonnyp** [comment]
no problem with a fresh git clone

**Comment by dhruvbird** [comment]
Yes, this is related to issue #33 - You can follow the steps mentioned there to fix it. Basically, log4js made a backward incompatible API change I believe and we had deps set up as >= instead of =. The next version (or the one after that) will have node-lumberjack as the logger (mostly), so these problems shouldn't arise.
