### ISSUE TITLE
Doubts about benchmarks

### ISSUE THREAD

**Issue by amolkul** [xmppo/node-xmpp-bosh#64]
I was checking the node-xmpp-benchmarks but I'm not sure if I understand it correctly and I have some doubts.

The wiki has foll sentence :
"BOSH server serving 1000 simultaneous BOSH sessions (clients) using 256 simultaneous HTTP connections."
1. How is it possible that the bosh server has 1k simultaneous connections but only 256 http connections ? 
2. Which xmpp server did you use for the tests ?
3. Do you have info about increase in cpu usage during the test?
4. Do you have a comparison with punjab?

**Comment by dhruvbird** [comment]
> The wiki has foll sentence :
> "BOSH server serving 1000 simultaneous BOSH sessions (clients) using 256 simultaneous HTTP connections."
> 
> How is it possible that the bosh server has 1k simultaneous connections but only 256 http connections ?

If you check the file https://github.com/dhruvbird/node-xmpp-bosh/blob/760c86983a1cf6fdcefd08335bcbbbf2579b6dd0/tests/stress.js you'll see that the agent is set to create only up to 256 concurrent http connections, but there are 1k active bosh sessions. This is of course not true with the latest version of the file since the node.js API has changed, and I haven't bothered re-running the benchmarks.

> Which xmpp server did you use for the tests ?

None - the file just sends a session start request and follows it up for an empty body on that session. The point was to test the bosh front-end. Though I agree that this doesn't account for state maintainer per XMPP connection to the XMPP server.

> Do you have info about increase in cpu usage during the test?

No. I don't recall recording this.

> Do you have a comparison with punjab?

No, but you can find some independent comparisons [online](https://github.com/jappix/jappix/wiki/BoshServer)
